# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        natural language processing: 2
        recommend: 2
        text: 1
        finance: 1
        bert: 1
        transformer: 1
        kaggle: 1


# 通知の閾値
score_threshold: 0
